User.create(username: "Chris", password: "123")
User.create(username: "Mark", password: "123")
User.create(username: "Evan", password: "123")
User.create(username: "Tony", password: "123")
User.create(username: "Jess", password: "123")

Restuarant.create(name: "Chipotle", user_id: 1, optional: false)
Restuarant.create(name: "Taco Madre", user_id: 1, optional: false)
Restuarant.create(name: "Portillos", user_id: 1, optional: false)
Restuarant.create(name: "Giordanos", user_id: 1, optional: false)
Restuarant.create(name: "Seven Treasures", user_id: 1, optional: false)
