Employee.create(username: "Chris", password: "123")
Employee.create(username: "Mark", password: "123")
Employee.create(username: "Evan", password: "123")
Employee.create(username: "Tony", password: "123")
Employee.create(username: "Jess", password: "123")

Restuarant.create(name: "Chipotle", employee_id: 1, optional: false)
Restuarant.create(name: "Taco Madre", employee_id: 1, optional: false)
Restuarant.create(name: "Portillos", employee_id: 1, optional: false)
Restuarant.create(name: "Giordanos", employee_id: 1, optional: false)
Restuarant.create(name: "Seven Treasures", employee_id: 1, optional: false)
