User.create(username: "Chris", password: "123")
User.create(username: "Mark", password: "123")
User.create(username: "Evan", password: "123")
User.create(username: "Tony", password: "123")
User.create(username: "Jess", password: "123")

Restuarant.create(name: "Chipotle", creator_id: 1, optional: false)
Restuarant.create(name: "Taco Madre", creator_id: 1, optional: false)
Restuarant.create(name: "Portillos", creator_id: 1, optional: false)
Restuarant.create(name: "Giordanos", creator_id: 1, optional: false)
Restuarant.create(name: "Seven Treasures", creator_id: 1, optional: false)
